// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/redis/go-redis/v9"
	account2 "user-server/biz/account"
	profile2 "user-server/biz/profile"
	"user-server/dao"
	"user-server/handler"
	"user-server/service/account"
	"user-server/service/profile"
)

// Injectors from wire.go:

func InitUserinfoHandler(dbMaster *dao.DBMaster, dbSlave *dao.DBSlave, clusterClient *redis.ClusterClient) *handler.UserinfoHandlerImpl {
	profileDao := dao.NewProfileDao(dbMaster, dbSlave, clusterClient)
	profileService := profile.NewProfileService(profileDao)
	profileBiz := profile2.NewProfileBiz(profileService)
	userDao := dao.NewUserDao(dbMaster)
	accountService := account.NewAccountService(userDao)
	accountBiz := account2.NewAccountBiz(accountService)
	userinfoHandlerImpl := handler.NewUserinfoHandlerImpl(profileBiz, accountBiz)
	return userinfoHandlerImpl
}
